// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEZblTie31y1YIa570w__PoafcFocAokA',
    appId: '1:301585141445:web:27fea4a7fc91522a336aac',
    messagingSenderId: '301585141445',
    projectId: 'automatic-watering-aaa74',
    authDomain: 'automatic-watering-aaa74.firebaseapp.com',
    databaseURL: 'https://automatic-watering-aaa74-default-rtdb.firebaseio.com',
    storageBucket: 'automatic-watering-aaa74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeL4ikEr2ZOfkVyxsZNyi0ckb5ibN1iWA',
    appId: '1:301585141445:android:f9bd54f863f207bd336aac',
    messagingSenderId: '301585141445',
    projectId: 'automatic-watering-aaa74',
    databaseURL: 'https://automatic-watering-aaa74-default-rtdb.firebaseio.com',
    storageBucket: 'automatic-watering-aaa74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu3UcqAT3b2hcQt5YpfYmd7pWijyK27Ik',
    appId: '1:301585141445:ios:463038f781828235336aac',
    messagingSenderId: '301585141445',
    projectId: 'automatic-watering-aaa74',
    databaseURL: 'https://automatic-watering-aaa74-default-rtdb.firebaseio.com',
    storageBucket: 'automatic-watering-aaa74.appspot.com',
    iosBundleId: 'com.example.software',
  );
}
